;;; dict.el --- Spelling, translating, …  -*- lexical-binding: t -*-

;; Copyright © 2014–2026 Alex Kost

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.
;;
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.


;;; Global keys

(al/bind-key "<XF86Spell>" al/translate-tui)

(al/bind-keys
 :prefix-map al/spell-map
 :prefix-docstring "Map for flyspell and friends."
 :prefix "H-s"
 ("r" . flyspell-region)
 ("b" . flyspell-buffer)
 ("n" . flyspell-goto-next-error)
 ("H-n" . flyspell-goto-next-error))


;;; Misc settings and packages

(al/with-eval-after-load ispell
  (ispell-change-dictionary "en" 'global))

(setopt flyspell-use-meta-tab nil)
(al/with-eval-after-load flyspell
  (defconst al/flyspell-keys
    '(("C-M-g n" . flyspell-goto-next-error))
    "Alist of auxiliary keys for `flyspell-mode-map'.")
  (al/bind-keys-from-vars 'flyspell-mode-map 'al/flyspell-keys))

(al/autoload "dictem"
  dictem-run-search
  dictem-run-match)

(al/with-eval-after-load dictem
  ;; Load "dictem-db.el" where I put `dictem-database-alist' and
  ;; `dictem-strategy-alist' generated by "M-x dictem-initialize".
  (al/load (al/emacs-data-dir-file "dictem-db"))
  (unless (and dictem-database-alist
               dictem-strategy-alist)
    (dictem-initialize))
  (setq dictem-use-existing-buffer nil)

  (al/bind-keys
    :map dictem-mode-map
    ("." . dictem-previous-link)
    ("e" . dictem-next-link)
    ("u" . dictem-define-on-press)
    ("h" . dictem-previous-section)
    ("n" . dictem-next-section)
    ("m" . dictem-hyperlinks-menu)
    ("M" . dictem-run-match)
    ("Q" . dictem-kill-all-buffers))

  (add-hook 'dictem-postprocess-match-hook
            #'dictem-postprocess-match)
  (add-hook 'dictem-postprocess-definition-hook
            #'dictem-postprocess-definition-separator)
  (add-hook 'dictem-postprocess-definition-hook
            #'dictem-postprocess-definition-hyperlinks)
  (add-hook 'dictem-postprocess-show-info-hook
            #'dictem-postprocess-definition-hyperlinks)

  (al/require al-dictem))

(al/with-eval-after-load al-dictem
  (setq al/dictem-dicts
        '(nil "mueller7" "korolew_en-ru" "korolew_ru-en"
              "slovnyk_ru-en" "ushakov" "fd-eng-lat" "fd-lat-eng"))
  (advice-add 'dictem :override #'al/dictem)
  (advice-add 'dictem-define-on-press
    :override #'al/dictem-define-on-press))

(al/with-eval-after-load google-translate-core-ui
  (setq
   google-translate-input-method-auto-toggling t
   google-translate-preferable-input-methods-alist
   '((dvorak-russian-computer "ru")
     (korean-hangul "ko"))
   google-translate-show-phonetic t
   google-translate-listen-program "mpv"
   google-translate-listen-button-label "Listen")
  (push '("Auto-detect" . "auto")
        google-translate-supported-languages-alist)

  (al/require al-google-translate))

(al/with-eval-after-load google-translate-smooth-ui
  (google-translate--setup-minibuffer-keymap)
  (defconst al/google-translate-keys
    '(("C-." . google-translate-previous-translation-direction)
      ("C-e" . google-translate-next-translation-direction))
    "Alist of auxiliary keys for `google-translate-minibuffer-keymap'.")
  (al/bind-keys-from-vars 'google-translate-minibuffer-keymap
    '(al/minibuffer-keys al/google-translate-keys))

  (al/add-hook-maybe 'google-translate-mode-hook 'al/text-scale+1))

(al/with-eval-after-load al-google-translate
  (advice-add 'google-translate-listen-translation
    :override #'al/google-translate-listen-translation))

;;; dict.el ends here
