;;; al-general.el --- Essential functionality for my config files  -*- lexical-binding: t -*-

;; Copyright © 2013–2026 Alex Kost

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.
;;
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; Code:

(eval-when-compile
  (require 'cl-lib)
  (require 'al-aux-macros)
  (require 'let-macros)
  (require 'fp-utils))

(require 'seq)
(require 'al-places)


;;; `rx' definitions

;; `lisp-mode.el' defines `lisp-mode-symbol' rx name.  However, it is
;; not documented anywhere, so I define `al/lisp-symbol' instead.
(rx-define al/lisp-symbol
  (+ (or (syntax word) (syntax symbol))))

(rx-define al/lisp-symbol-group
  (group al/lisp-symbol))

(rx-define al/space
  (+ (or " " "\t")))

(rx-define al/space*
  (* (or " " "\t")))


;;; Simple wrappers for hooks

(defun al/show-trailing-whitespace ()
  (setq-local show-trailing-whitespace t))

(defun al/no-truncate-lines ()
  (setq-local truncate-lines nil))

(defun al/inhibit-field-motion ()
  (setq-local inhibit-field-text-motion t))

(defun al/bar-cursor-type ()
  (setq-local cursor-type 'bar))

(defun al/hbar-cursor-type ()
  (setq-local cursor-type 'hbar))

(defun al/no-syntactic-font-lock ()
  (setq-local font-lock-keywords-only t))

(defun al/set-comment-column ()
  (setq-local comment-column 32))

(defun al/set-default-paragraph ()
  (setq-local paragraph-start    (default-value 'paragraph-start)
              paragraph-separate (default-value 'paragraph-separate)))

(defun al/text-scale+1 ()
  "Increase the font size in the current buffer by 1."
  (text-scale-increase 1))


;;; Function utils

(defun al/funcall (function &rest arguments)
  "Call FUNCTION with ARGUMENTS.
This is the same as `funcall' except it returns nil instead of error if
FUNCTION does not exist."
  (and (al/function? function)
       (apply function arguments)))

(defun al/funcall-or-dolist (val function)
  "Call FUNCTION on VAL if VAL is not a list.
If VAL is a list, call FUNCTION on each element of the list."
  (declare (indent 1))
  (if (listp val)
      (dolist (v val)
        (funcall function v))
    (funcall function val)))


;;; Key binding utils

(defvar al/override-global-map (make-keymap)
  "Keymap with key bindings to take precedence over other keymaps.")

(define-minor-mode al/override-global-mode
  "Minor mode with key bindings to override other modes."
  :init-value t)

(push `((al/override-global-mode . ,al/override-global-map))
      emulation-mode-map-alists)

(defvar al/self-insert-commands
  '(undefined
    self-insert-command
    isearch-printing-char
    org-self-insert-command
    picture-self-insert)
  "List of self-inserting commands.")

(defun al/key-if-bound (key &optional fallback-key)
  "Return KEY if it is bound in the currently active keymaps.

Return FALLBACK-KEY, if KEY is not bound or bound to one of
`al/self-insert-commands' commands.

This is a helper function called by functions generated by
`al/translate-keys' macro."
  (cl-flet ((key (cmd)
              (if (and cmd
                       (not (memq cmd al/self-insert-commands)))
                  key
                fallback-key)))
    ;; Ideally, if `overriding-terminal-local-map' is active, it should
    ;; be checked instead of the current maps (`key-binding' does not
    ;; check `overriding-terminal-local-map' because the latter
    ;; overrides global keys)…  However, this map is used by such
    ;; things as `isearch' and `set-transient-map' which fall back to
    ;; the current maps, so we also need to check the current maps…
    ;; However, this map is used by `transient' which never falls back
    ;; and expects a key only from `overriding-terminal-local-map', so
    ;; we should not check the current maps for `transient'.
    (or (and overriding-terminal-local-map
             (if-let ((cmd (lookup-key overriding-terminal-local-map
                                       key)))
                 (key cmd)
               ;; Is there a better way to check if `transient' is in
               ;; progress?
               (and (or (bound-and-true-p transient--transient-map)
                        (lookup-key overriding-terminal-local-map
                                    fallback-key))
                    fallback-key)))
        ;; We cannot simply check if KEY is bound because KEY is not the
        ;; whole key sequence, it is always a vector with the last key
        ;; of the sequence.  For example, assume "e" is translated to
        ;; "↓", and "↓" is bound in the current major mode.  Then,
        ;; when "C-h e" is pressed, and only KEY is checked with
        ;; `key-binding', Emacs will tell "C-h ↓ is undefined".  That's
        ;; why we need to check the whole key sequence ("C-h ↓" instead
        ;; of just "↓") by replacing the last key from the current
        ;; sequence with KEY.
        (let ((key-seq (this-single-command-keys)))
          (aset key-seq
                (1- (length key-seq))
                (aref key 0))
          (key (key-binding key-seq))))))

(defun al/clean-keymap (keymap &optional clean-parent)
  "Remove all key bindings from KEYMAP.
If CLEAN-PARENT is non-nil, also remove the parent keymap."
  (if clean-parent
      (setcdr keymap nil)
    (let ((parent (keymap-parent keymap)))
      (setcdr keymap nil)
      (set-keymap-parent keymap parent))))


;;; Auxiliary messages

(defmacro al/define-message (name string)
  "Define `al/NAME-string' and `al/NAME-message' functions."
  (declare (indent 0) (debug t))
  (let* ((name-str (symbol-name name))
         (str-name (intern (concat "al/" name-str "-string")))
         (msg-name (intern (concat "al/" name-str "-message"))))
    `(progn
       (defun ,str-name (format-string &rest args)
         ,(concat "Return " name-str " string.")
         (apply #'format
                (concat ,string format-string)
                args))

       (defun ,msg-name (format-string &rest args)
         ,(concat "Display " name-str " message.")
         (message (apply #',str-name format-string args))))))

(al/define-message error "ERROR: ")
(al/define-message warning "WARNING: ")
(al/define-message important "XXX ")
(al/define-message title "⏺ ")


;;; Auxiliary predicates

(defun al/p (predicate val &optional message)
  "Return non-nil if PREDICATE returns non-nil on VAL.
Otherwise display warning MESSAGE on VAL and return nil."
  (or (funcall predicate val)
      (progn (and message (al/warning-message message val))
             nil)))

(defun al/every? (predicate vals &optional message)
  "Return non-nil if PREDICATE returns non-nil on each element of VALS.
If VALS is not a list, call PREDICATE on this value."
  (if (and (listp vals)
           (not (functionp vals))) ; to avoid treating "(lambda …)" as list
      (seq-every-p (cut #'al/p predicate <> message)
                   vals)
    (al/p predicate vals message)))

(defun al/function? (object)
  "Non-nil if OBJECT is a function or a list of functions."
  (al/every? #'functionp object
             "Unknown function `%S'."))

(defun al/bound? (object)
  "Non-nil if OBJECT is a bound symbol or a list of bound symbols."
  (al/every? #'boundp object
             "Symbol `%S' is not bound."))

(defun al/file? (object)
  "Non-nil if OBJECT is an existing file or a list of directories."
  (al/every? #'file-exists-p object
             "File `%s' does not exist."))

(defun al/directory? (object)
  "Non-nil if OBJECT is an existing directory or a list of directories."
  (al/every? #'file-directory-p object
             "Directory `%s' does not exist."))

(defmacro al/with-check (&rest body)
  "Call rest of BODY if all checks are passed successfully.

BODY should start with checks (keyword arguments).  The following
keywords are available: `:fun'/`:var'/`:file'/`:dir'.  Each
keyword argument may be an object or a list of objects.  These
objects are checkced to be a proper function / a bound symbol /
an existing file / an existing directory.

Return nil if checks are not passed."
  (declare (indent 0) (debug (name body)))
  (al/with-keywords body
      (fun var file dir)
    (let ((check-list
           (list (and fun  `(al/function?  ,fun))
                 (and var  `(al/bound?     ,var))
                 (and file `(al/file?      ,file))
                 (and dir  `(al/directory? ,dir)))))
      `(if ,(pcase (delq nil check-list)
              (`(,check) check)
              (_ `(and ,@check-list)))
           ,(macroexp-progn %body)))))


;;; (Auto)loading utils

(defun al/add-to-load-path-maybe (&rest dirs)
  "Add existing directories from DIRS to `load-path'."
  (dolist (dir dirs)
    (al/with-check
      :dir dir
      (push dir load-path))))

(defun al/load (file)
  "Load FILE.
Return t if FILE is loaded successfully, nil otherwise.
FILE may omit an extension.  See `load' for details."
  (al/with-demoted-errors
      (concat "Failed to load `" file "': %S")
    (load file)))

(defun al/load-init (&rest files)
  "Load FILES from `al/emacs-init-dir'."
  (dolist (file files)
    (al/load (al/emacs-init-dir-file file))))

(defun al/load-settings (&rest files)
  "Load FILES from `al/emacs-settings-dir'."
  (dolist (file files)
    (al/load (al/emacs-settings-dir-file file))))

(defvar al/load-paths nil
  "List of `load-path' lists added by `al/load-autoloads'.")

(declare-function al/generate-autoloads "al-autoload")

(defun al/load-autoloads (name directory autoloads-file &rest args)
  "Load AUTOLOADS-FILE, generate it for DIRECTORY if needed.

NAME is a string used for messages.

Additional ARGS are sent to `al/generate-autoloads'.

Push added `load-path' to `al/load-paths'."
  (when (file-exists-p directory)
    (unless (file-exists-p autoloads-file)
      (al/with-demoted-errors
          (concat "Generating " name " autoloads failed: %S")
        (require 'al-autoload)
        (apply #'al/generate-autoloads directory
               :output-file autoloads-file
               args)))
    (al/with-demoted-errors
        (concat "Loading " name " autoloads failed: %S")
      (let ((count (length load-path)))
        (al/load autoloads-file)
        (push (seq-subseq load-path 0 (- count))
              al/load-paths)))))

(defun al/simple-eval-after-load (feature function)
  "Simplified version of `eval-after-load'.
If FEATURE is already loaded, call FUNCTION.
Otherwise, add FUNCTION to `after-load-alist'."
  (if (featurep feature)
      (funcall function)
    (if-let ((elt (assoc feature after-load-alist)))
        (nconc elt (list function))
      (push (list feature function)
            after-load-alist))))


;;; Miscellaneous utils

(defun al/intern (string-or-symbol)
  "Like `intern' except STRING-OR-SYMBOL can also be a symbol."
  (if (symbolp string-or-symbol)
      string-or-symbol
    (intern string-or-symbol)))

(defun al/init-time (&optional format)
  "Return a string with duration of my config initialization.
This is similar to `emacs-init-time' except it returns the time passed
from `al/before-init-time' to `al/after-init-time'."
  (let ((before (bound-and-true-p al/before-init-time))
        (after  (bound-and-true-p al/after-init-time)))
    (if (and before after)
        (format (or format "%f seconds")
                (float-time (time-subtract after before)))
      (al/warning-message
       "`al/before-init-time' and `al/after-init-time' should be set"))))

(provide 'al-general)

;;; al-general.el ends here
